[mysql2]
host = "localhost"
user = "root"
database = "DHARMAREDDY"
password ="Vnr@2003"


        # ... rest of your Streamlit app ...

    # Close the connection when done (important!)
    conn.close()
else:
    st.error("Failed to connect to the database. Please check your connection parameters in secrets.toml.")
